version: '3.8'
services:
  postgres_db:
    image: postgres
    volumes:
    - ./db/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432